### ISSUE TITLE
crash on startup, probably for lack of .tabby

### ISSUE THREAD

**Issue by Nazgand** [mikhailt/tabby#1]
tabby: unable to Open file for reading:  /home/mark/.tabby
panic: runtime error: invalid memory address or nil pointer dereference

panic PC=0x7f51ec77db98
runtime.panic+0xb2 /home/mark/go/src/pkg/runtime/proc.c:1028
        runtime.panic(0x488fac, 0x7f51ec77a4c0)
runtime.panicstring+0x69 /home/mark/go/src/pkg/runtime/runtime.c:86
        runtime.panicstring(0x626367, 0x7f51ec7bd180)
runtime.sigpanic+0x144 /home/mark/go/src/pkg/runtime/linux/thread.c:286
        runtime.sigpanic()
bufio._Reader·ReadSlice+0x61 /home/mark/go/src/pkg/bufio/bufio.go:251
        bufio._Reader·ReadSlice(0x0, 0x7f51ec70a, 0x0, 0x0, 0x0, ...)
bufio._Reader·ReadBytes+0xdd /home/mark/go/src/pkg/bufio/bufio.go:300
        bufio._Reader·ReadBytes(0x0, 0x40d10a, 0x0, 0x0, 0x0, ...)
bufio._Reader·ReadString+0x59 /home/mark/go/src/pkg/bufio/bufio.go:338
        bufio._Reader·ReadString(0x0, 0x20041360a, 0x0, 0x0, 0x0, ...)
main.next_string_from_reader+0x2a /home/mark/tabby/src/session.go:72
        main.next_string_from_reader(0x0, 0x7f51ec77a4b0, 0x0, 0x0, 0x7, ...)
main.session_restore+0xc4 /home/mark/tabby/src/session.go:52
        main.session_restore()
main.init_vars+0x6a /home/mark/tabby/src/main.go:230
        main.init_vars()
main.init_tabby+0x18c5 /home/mark/tabby/src/main.go:218
        main.init_tabby()
main.main+0x29 /home/mark/tabby/src/main.go:236
        main.main()
runtime.mainstart+0xf /home/mark/go/src/pkg/runtime/amd64/asm.s:77
        runtime.mainstart()
runtime.goexit /home/mark/go/src/pkg/runtime/proc.c:146
        runtime.goexit()

goroutine 2 [3]:
runtime.entersyscall+0x28 /home/mark/go/src/pkg/runtime/proc.c:567
        runtime.entersyscall()
syscall.Syscall+0x5 /home/mark/go/src/pkg/syscall/asm_linux_amd64.s:15
        syscall.Syscall()
syscall.Read+0x66 /home/mark/go/src/pkg/syscall/zsyscall_linux_amd64.go:472
        syscall.Read(0x6, 0x7f51ec84d000, 0x400000004000, 0x7f51ec7abee0, 0x100000001, ...)
main.inotify_observe_collect+0xa4 /home/mark/tabby/src/inotify.go:110
        main.inotify_observe_collect(0x7f51ec84d000, 0x400000004000, 0x4000, 0x7f51ec84d000, 0x400000004000, ...)
main.inotify_observe+0x9d /home/mark/tabby/src/inotify.go:70
        main.inotify_observe()
runtime.goexit /home/mark/go/src/pkg/runtime/proc.c:146
        runtime.goexit()

**Comment by mikhailt** [comment]
Thank you. Just say "touch ~/.tabby"

**Comment by Nazgand** [comment]
I tried that, But I am still getting the same error. 
I then tried "echo -e '\n'>~/.tabby", and got a messagebox saying "Unable to open file for reading:"
I then tried "echo -e '\n\n\n\n\n'>~/.tabby", and got 5 messageboxes saying "Unable to open file for reading:"

the program quit each time. If I can fix it, I will fork, push, and ask for pull.

**Comment by Nazgand** [comment]
I got it working!
"touch ~/.tabby"
"touch ~/.tabbyignore"
I suppose the simplest thing to do is create these files if they don't exist at the beginning of main().

**Comment by mikhailt** [comment]
Good point, Nazgand, thank you. I will make tabby more working-from-the-box soon with all the readme & screenshots, etc.
