### ISSUE TITLE
change in go-gtk: GValue now lives in glib

### ISSUE THREAD

**Issue by soul9** [mikhailt/tabby#5]
change gtk.GValue to glib.GValue in main.go and tree_view.go
patch in comment

**Comment by soul9** [comment]
<pre>
diff --git a/src/main.go b/src/main.go
index fe8bff6..08d88a1 100644
--- a/src/main.go
+++ b/src/main.go
@@ -3,6 +3,7 @@ package main
 import (
    "gtk"
    "gdk"
+   "glib"
    "file_tree"
 )
 
@@ -40,7 +41,7 @@ func refresh_title() {
        icon = 'B'
    }
    if tree_store.IterIsValid(&cur_iter) {
-       var val gtk.GValue
+       var val glib.GValue
        tree_model.GetValue(&cur_iter, 0, &val)
        tree_store.Set(&cur_iter, string(icon)+val.GetString()[1:])
    }
diff --git a/src/tree_view.go b/src/tree_view.go
index 35b1f72..8d70868 100644
--- a/src/tree_view.go
+++ b/src/tree_view.go
@@ -2,6 +2,7 @@ package main
 
 import (
    "gtk"
+   "glib"
    "strings"
 )
 
@@ -39,7 +40,7 @@ func tree_view_get_selected_path(tree_view *gtk.GtkTreeView, tree_model *gtk.Gtk
    var ans string
    ans = ""
    for {
-       var val gtk.GValue
+       var val glib.GValue
        var next gtk.GtkTreeIter
        tree_model.GetValue(&iter, col, &val)
        if shift {
@@ -65,7 +66,7 @@ func tree_view_set_cur_iter(mark bool) {
    name := cur_file
    tree_model.GetIterFirst(&cur_iter)
    for {
-       var val gtk.GValue
+       var val glib.GValue
        tree_model.GetValue(&cur_iter, 0, &val)
        whole_string := val.GetString()
        cur_str := whole_string[1:]
</pre>

**Comment by mikhailt** [comment]
Done, thanks
